services:
  cassandra:
    image: cassandra:5.0.1
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=Test Cluster
      - CASSANDRA_SEEDS=cassandra
    ports:
      - "${CASSANDRA_PORT}:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./init_cassandra.sh:/docker-entrypoint-initdb.d/init_cassandra.sh # Adding the init script
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - cassandra
      - redis
    env_file:
      - .env
volumes:
  cassandra-data:
  redis-data:
